# tasks/urls.py
"""
This module defines the URL routing for the tasks application within the task_manager project.

It utilizes Django's URL dispatcher to map URL patterns to views. The DefaultRouter from Django REST Framework is used to automatically generate the URL conf for the TaskViewSet and UserViewSet, which handle the CRUD operations for tasks and users, respectively.

The following routes are defined:
- The base route ('') includes all the routes generated by the router for tasks and users.
- A specific route ('tasks/user/<int:user_id>/') is defined to retrieve tasks associated with a specific user, utilizing the 'get_tasks_for_user' method from the TaskViewSet.

This setup allows for a clean and organized way to manage API endpoints related to tasks and users.
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TaskViewSet, UserViewSet

router = DefaultRouter()
router.register(r'tasks', TaskViewSet, basename='task')  # for the TaskViewSet class register the tasks
router.register(r'users', UserViewSet, basename='user')  # for the UserViewSet class register the users

urlpatterns = [
    path('', include(router.urls)),
    path('tasks/user/<int:user_id>/', TaskViewSet.as_view({'get': 'get_tasks_for_user'}), name='tasks-for-user'),
    path('tasks/<int:pk>/assign/', TaskViewSet.as_view({'post': 'assign'}), name='assign-users-to-task'), 
    path('tasks/<int:pk>/', TaskViewSet.as_view({'delete': 'destroy'}), name='delete-task'),  
]